[package]
name = "ssh-git"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.42.0", features = ["full"] }
russh = { version = "0.49.2" }
async-trait = "0.1.83"
uuid = { version = "1.11.0", features = ["v4"] }
russh-keys = "0.49.2"
