[package]
name = "ssh-git"
version = "0.1.0"
edition = "2021"

[dependencies]
tokio = { version = "1.44.1", features = ["full"] }
russh = { version = "0.51.1" }
uuid = { version = "1.16.0", features = ["v4"] }
