[package]
name = "ssh-git"
version = "1.0.0"
edition = "2021"

[dependencies]
tokio = { version = "1.45.1", features = ["full"] }
russh = { version = "0.52.1" }
uuid = { version = "1.17.0", features = ["v4"] }
chrono = "0.4.41"
regex = "1.11.1"
